services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7832705502:AAFqWpFOZkoFROHMZS1ssT1KcHYhT8CnNX0
